### ISSUE TITLE
Unable to get starter app working

### ISSUE THREAD

**Issue by BobKlaas** [mikecallahan/cfalexa#1]
I wasn't able to get your starter skill working using your starter guide for the "My Voice Template". The error I receive from Amazon when testing is "There was a problem with the requested skill's response". I followed your .PDF guide verbatim. 

I'm assuming it has to do with my endpoint. Although, based on your guide, all you do is drop the files in the root and update the skill id in the CFC. Which, I did both. How do you debug from here? Do you use Postman?

**Comment by mikecallahan** [comment]
Hi Robert, yes I use Postman to debug. Copy your endpoint from the Alexa Developer Console and paste it into the "Post" text box in Postman.  Then copy the JSON input from the test section of the console and past it into the "Body" section in Postman.  Now hit the Send button in Postman and you should see the results in the "Response" section.  It's usually informative enough to steer you in the right direction.  Double check that your Skill ID is correct in your voicetemplate.cfc.  I'm assuming your ColdFusion website (i.e. your endpoint) is available and accessible to the public, if not Alexa cannot access the endpoint and you will get an error.  Also make sure your site is using a security certificate, Alexa enforces security by requiring "https" otherwise you will get an error.  

Hopefully Postman will point out what the specific issue is.  Good luck and let me know if can hep in any other way.

**Comment by BobKlaas** [comment]
Got it. Via postman, I was able to determine that my Application.cfc was hijacking the service request and re-routing it to my login page. Once I fixed that, the test starting working via the alexa skills testing tool. Thanks for your help Mike.

**Comment by mikecallahan** [comment]
That's great, I'm glad it's working for you!  If you want to try out some more examples go to www.cfalexa.com and check out the "Examples" section.  Each example presents a little something different and new.  Good luck!

**Comment by mikecallahan** [comment]
Thanks for having a look at cfalexa!
